interactions:
- request:
    body: null
    headers:
      Accept: ['*/*']
      Accept-Encoding: ['gzip, deflate']
      Connection: [keep-alive]
      User-Agent: [python-requests/2.12.1]
    method: GET
    uri: https://geobigdata.io/catalog/v2/record/10400100203F1300?includeRelationships=false
  response:
    body: {string: !!python/unicode "\n{\n  \"status\": \"401 Unauthorized\",\n  \"\
        message\" : \"Authentication Failed.\"\n}\n"}
    headers:
      access-control-allow-origin: ['*']
      connection: [keep-alive]
      content-length: ['76']
      content-type: [application/json]
      date: ['Mon, 27 Mar 2017 18:11:42 GMT']
      via: [kong/0.5.2]
      x-amz-cf-id: [5NrNshFsTL9yv4xEGeSKaELyDwmtEadhikNoRpjRK4aEXPaS5O2gyQ==]
      x-amzn-requestid: [d4a69867-1318-11e7-8be5-13303f3bd176]
      x-amzn-trace-id: [Root=1-58d955de-8e85db7f556b78100318b2ba]
      x-cache: [Error from cloudfront]
    status: {code: 401, message: Unauthorized}
version: 1
