interactions:
- request:
    body: null
    headers:
      Accept: ['*/*']
      Accept-Encoding: ['gzip, deflate']
      Connection: [keep-alive]
      User-Agent: [python-requests/2.12.1]
    method: GET
    uri: https://geobigdata.io/catalog/v2/record/nonexistent_asdfasdfasdfdfasffds?includeRelationships=false
  response:
    body: {string: !!python/unicode "\n{\n  \"status\": \"404 Not Found\",\n  \"message\"\
        \ : \"Not Found: nonexistent_asdfasdfasdfdfasffds\"\n}\n"}
    headers:
      access-control-allow-origin: ['*']
      connection: [keep-alive]
      content-length: ['94']
      content-type: [application/json]
      date: ['Mon, 27 Mar 2017 19:16:01 GMT']
      via: [kong/0.5.2]
      x-amz-cf-id: [AqRn2c7tBKHE9ZP0H9QHgm1FoCC6_v3LTkO5mxkjs-93W2cUuDyIhQ==]
      x-amzn-requestid: [d0e9ef68-1321-11e7-b54f-bfdc0e07b577]
      x-amzn-trace-id: [Root=1-58d964f1-b69811ae4eb15732c86e9521]
      x-cache: [Error from cloudfront]
    status: {code: 404, message: Not Found}
version: 1
