interactions:
- request:
    body: null
    headers:
      Accept: ['*/*']
      Accept-Encoding: ['gzip, deflate']
      Connection: [keep-alive]
      User-Agent: [python-requests/2.12.1]
    method: GET
    uri: https://geobigdata.io/catalog/v2/record/10400100203F1300?includeRelationships=false
  response:
    body: {string: !!python/unicode "\n{\n  \"status\": \"401 Unauthorized\",\n  \"\
        message\" : \"Authentication Failed.\"\n}\n"}
    headers:
      access-control-allow-origin: ['*']
      connection: [keep-alive]
      content-length: ['76']
      content-type: [application/json]
      date: ['Mon, 27 Mar 2017 19:53:34 GMT']
      via: [kong/0.5.2]
      x-amz-cf-id: [4e9JPhdSrVLL5PdGi9COxMY5UW_vc_lfeBnX1dR10XcxiLXfxK57Mw==]
      x-amzn-requestid: [0fa5688b-1327-11e7-9942-57c9d44b0c8b]
      x-amzn-trace-id: [Root=1-58d96dbe-12f27d786537064a506efc41]
      x-cache: [Error from cloudfront]
    status: {code: 401, message: Unauthorized}
version: 1
