interactions:
- request:
    body: null
    headers:
      Accept: ['*/*']
      Accept-Encoding: ['gzip, deflate']
      Connection: [keep-alive]
      User-Agent: [python-requests/2.12.1]
    method: GET
    uri: https://geobigdata.io/catalog/v2/record/10400100203F1300?includeRelationships=false
  response:
    body: {string: !!python/unicode "\n{\n  \"status\": \"401 Unauthorized\",\n  \"\
        message\" : \"Authentication Failed.\"\n}\n"}
    headers:
      access-control-allow-origin: ['*']
      connection: [keep-alive]
      content-length: ['76']
      content-type: [application/json]
      date: ['Mon, 27 Mar 2017 19:25:54 GMT']
      via: [kong/0.5.2]
      x-amz-cf-id: [q40ngqMK1JhxkpU_H16IhujaJ9ZflgGKZePbZ0aE6kVe7k5stDRP8Q==]
      x-amzn-requestid: [3235a93d-1323-11e7-af44-39be51ff3916]
      x-amzn-trace-id: [Root=1-58d96742-a43b0bff685eb5f4657e756c]
      x-cache: [Error from cloudfront]
    status: {code: 401, message: Unauthorized}
version: 1
