interactions:
- request:
    body: null
    headers:
      Accept: ['*/*']
      Accept-Encoding: ['gzip, deflate']
      Connection: [keep-alive]
      User-Agent: [python-requests/2.12.1]
    method: GET
    uri: https://geobigdata.io/catalog/v2/record/10400100203F1300?includeRelationships=false
  response:
    body: {string: !!python/unicode "\n{\n  \"status\": \"401 Unauthorized\",\n  \"\
        message\" : \"Authentication Failed.\"\n}\n"}
    headers:
      access-control-allow-origin: ['*']
      connection: [keep-alive]
      content-length: ['76']
      content-type: [application/json]
      date: ['Mon, 27 Mar 2017 19:25:54 GMT']
      via: [kong/0.5.2]
      x-amz-cf-id: [nEvVwVvBkDe6nCCHPUQ0CZ9rL4-ljIPEnOLRKqTyLY_fPlyqXeHMDA==]
      x-amzn-requestid: [31d86da9-1323-11e7-8098-bd3948e17435]
      x-amzn-trace-id: [Root=1-58d96741-67ad755616cb9c0197f13647]
      x-cache: [Error from cloudfront]
    status: {code: 401, message: Unauthorized}
version: 1
