interactions:
- request:
    body: null
    headers:
      Accept: ['*/*']
      Accept-Encoding: ['gzip, deflate']
      Connection: [keep-alive]
      User-Agent: [python-requests/2.13.0]
    method: GET
    uri: https://idahoapi.geobigdata.io/v1/metadata/idaho-virtual/no_id/toa_reflectance/image.json
  response:
    body: {string: !!python/unicode '{"message":"graph id no_id does not exist","exceptionType":"IPEServiceNotFoundException"}'}
    headers:
      access-control-allow-headers: ['x-requested-with, X-Auth-Token, Content-Type,
          Authorization']
      access-control-allow-methods: ['GET, OPTIONS, HEAD, PUT, POST, DELETE']
      access-control-allow-origin: ['*']
      access-control-max-age: ['3600']
      connection: [keep-alive]
      content-length: ['89']
      content-type: [application/json]
      date: ['Mon, 26 Jun 2017 17:06:58 GMT']
    status: {code: 404, message: Not Found}
version: 1
