interactions:
- request:
    body: null
    headers:
      Accept: ['*/*']
      Accept-Encoding: ['gzip, deflate']
      Connection: [keep-alive]
      User-Agent: [python-requests/2.12.1]
    method: GET
    uri: https://geobigdata.io/catalog/v2/record/10400100203F1300?includeRelationships=false
  response:
    body: {string: !!python/unicode "\n{\n  \"status\": \"401 Unauthorized\",\n  \"\
        message\" : \"Authentication Failed.\"\n}\n"}
    headers:
      access-control-allow-origin: ['*']
      connection: [keep-alive]
      content-length: ['76']
      content-type: [application/json]
      date: ['Mon, 27 Mar 2017 19:53:35 GMT']
      via: [kong/0.5.2]
      x-amz-cf-id: [puwHl4fLOj9G8oo_YnZlbapl_6aexoUIdnWiEOvYLHgvYQ2sI6PFvQ==]
      x-amzn-requestid: [102016c0-1327-11e7-b913-0d880216e4be]
      x-amzn-trace-id: [Root=1-58d96dbf-48bfd1cf2d93a7f31ff4f7df]
      x-cache: [Error from cloudfront]
    status: {code: 401, message: Unauthorized}
version: 1
