interactions:
- request:
    body: null
    headers:
      Accept: ['*/*']
      Accept-Encoding: ['gzip, deflate']
      Connection: [keep-alive]
      User-Agent: [python-requests/2.12.1]
    method: GET
    uri: https://geobigdata.io/catalog/v2/record/10400100203F1300?includeRelationships=false
  response:
    body: {string: !!python/unicode "\n{\n  \"status\": \"401 Unauthorized\",\n  \"\
        message\" : \"Authentication Failed.\"\n}\n"}
    headers:
      access-control-allow-origin: ['*']
      connection: [keep-alive]
      content-length: ['76']
      content-type: [application/json]
      date: ['Mon, 27 Mar 2017 17:09:04 GMT']
      via: [kong/0.5.2]
      x-amz-cf-id: [dTUx0zJGbdzVla8Xd6OO2Ya-oAq2m-wonf5Nrs4o1Hro5L5LZOIP5w==]
      x-amzn-requestid: [142fa327-1310-11e7-9218-75a2896acab6]
      x-amzn-trace-id: [Root=1-58d9472f-455db37d477549c9c2460c15]
      x-cache: [Error from cloudfront]
    status: {code: 401, message: Unauthorized}
version: 1
